#%RAML 1.0 Trait
usage: apply this traits for Client-id authentication
headers:
  client-id:
    type: string
    required: true
    description: client secret to authenticate to system api
  client-secret:
    type: string
    required: true
    description: client secret to authenticate to system api